### ISSUE TITLE
How to apply options to embed link

### ISSUE THREAD

**Issue by devRMA** [KaneCohen/oembed#2]
I want to add the ``autoplay`` option with the value ``1`` to the youtube url, I tried to do this

```php
$embed = OEmbed::get('http://youtu.be/FOOBAR');
echo $embed->html([autoplay=> '1']);
```

I expected to get the url ``https://www.youtube.com/embed/FOOBAR?feature=oembed&autoplay=1``, but this option was not applied to the url. How could I do this?

**Comment by KaneCohen** [comment]
Currently as there's no way to enable autoplay like that - library returns "url" that YouTube (or any other oembed provider) returns. I'll check today for a way to implement autoplay.

Main problem is that it's not possible to just add "autoplay" flag - since different providers might have different ideas on how to enable autoplay on their embed objects. So it would have to be something fairly generic.

**Comment by KaneCohen** [comment]
Pushed `v0.10` which allows adding of `autoplay` option in `html()`, `ampHtml()` and `src()` methods.

While at it I added `src()` method which, depending on the embed type, will return a URL of the current embed object itself, instead of `url()` method which returns url that you provided to OEmbed.
